/*
 * This file was automatically generated by EvoSuite
 * Tue Dec 04 00:48:00 GMT 2018
 */

package system.controller;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import system.controller.ResultController;
import system.controller.dao.ResultDao;
import system.controller.service.ResultService;
import system.model.Result;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class ResultController_ESTest extends ResultController_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Object object0 = ResultController.__CLR4_1_2169169jp8v55ug.lambdaInc((-80), "\"Hg )\"", 1787);
      assertNotNull(object0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      ResultController.__CLR4_1_2169169jp8v55ug resultController___CLR4_1_2169169jp8v55ug0 = new ResultController.__CLR4_1_2169169jp8v55ug();
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      system.controller.ResultController resultController0 = new system.controller.ResultController();
      // Undeclared exception!
      try { 
        resultController0.remove("Cannot parse date value \"");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("system.controller.ResultController", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      system.controller.ResultController resultController0 = new system.controller.ResultController();
      Double double0 = new Double((-0.12345));
      // Undeclared exception!
      try { 
        resultController0.grade("x\")fBM", (-195), "<SG9Y", double0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("system.controller.ResultController", e);
      }
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      system.controller.ResultController resultController0 = new system.controller.ResultController();
      Result result0 = new Result("Accept-Ranges");
      // Undeclared exception!
      try { 
        resultController0.edit(result0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("system.controller.ResultController", e);
      }
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      system.controller.ResultController resultController0 = new system.controller.ResultController();
      Result result0 = new Result();
      // Undeclared exception!
      try { 
        resultController0.add(result0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("system.controller.ResultController", e);
      }
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      system.controller.ResultController resultController0 = new system.controller.ResultController();
      ResultService resultService0 = new ResultService();
      ResultDao resultDao0 = new ResultDao();
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      system.controller.ResultController resultController0 = new system.controller.ResultController();
      // Undeclared exception!
      try { 
        resultController0.getAll((String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("system.controller.ResultController", e);
      }
  }
}
